"""Truthful capability registry for JENNY.

Why this file exists
--------------------
The request was to "add all these skills". Adding ~800 name->phrase mappings
with nothing behind them would recreate the exact false-success bug found in
the audit (see server.py:4092-4094, where an uninstalled app still reports
success). So instead of inflating the alias catalog, every requested capability
is recorded here against its REAL backing, and JENNY reports the gap instead of
hiding it.

Status codes
------------
W:<executor>  works now, deterministic executor named
P:<executor>  partially works, executor named (narrower than requested)
M             genuinely handled by the Groq model in conversation
              (real, but generative -- not a deterministic action)
C:<what>      needs a credential we do not have (API key / account / login)
S:<what>      needs hardware, an external service, or an integration that
              does not exist on this machine
N             not implemented, and nothing pretends otherwise

Nothing in this file invents a capability. `summary()` is what /api/capabilities
reports, and it is expected to show large N/S/C counts -- that is the truth.
"""

from __future__ import annotations

#: Real executors discovered in the codebase, with what they actually do.
EXECUTORS = {
    "pc_actions.open_app": "launch a detected, installed app",
    "pc_actions.close_window_focused": "close the focused window",
    "pc_actions.browser_open": "open a URL in the default browser",
    "pc_actions.browser_search": "search the web in the browser",
    "pc_actions.browser_new_tab": "open a new browser tab",
    "pc_actions.browser_close_tab": "close the active tab",
    "pc_actions.browser_back": "browser back",
    "pc_actions.browser_forward": "browser forward",
    "pc_actions.browser_refresh": "reload the page",
    "pc_actions.browser_new_window": "open a new browser window",
    "pc_actions.browser_reopen_tab": "reopen a closed tab",
    "pc_actions.browser_fullscreen": "toggle browser fullscreen",
    "pc_actions.browser_youtube": "open YouTube",
    "pc_actions.browser_gmail": "open Gmail",
    "pc_actions.browser_github": "open GitHub",
    "pc_actions.volume_up": "raise system volume",
    "pc_actions.volume_down": "lower system volume",
    "pc_actions.volume_mute": "toggle mute",
    "pc_actions.media_play_pause": "media key play/pause",
    "pc_actions.media_next": "media key next track",
    "pc_actions.media_prev": "media key previous track",
    "pc_actions.screenshot": "capture the screen to a file",
    "pc_actions.open_task_manager": "open Task Manager",
    "pc_actions.show_desktop": "minimise everything (show desktop)",
    "pc_actions.lock_pc": "lock the workstation",
    "pc_actions.lock_screen_timer": "lock after a short countdown",
    "pc_actions.clipboard_read": "read the Windows clipboard (control: clipboard-read)",
    "pc_actions.clipboard_write": "write text to the Windows clipboard (control: clipboard-write)",
    "pc_actions.file_search": "recursive filename search in Desktop/Documents/Downloads (control: file-search)",
    "pc_actions.recent_files": "list recently opened files (control: recent-files)",
    "pc_actions.large_files": "find the largest files in a folder (control: large-files)",
    "pc_actions.list_processes": "list running processes with memory use",
    "pc_actions.startup_apps": "list configured startup entries (control: startup-apps)",
    "pc_actions.system_diagnostics": "battery/cpu/ram/disk/network snapshot (control: system-diagnostics)",
    "app_integrations.focus_window": "focus a window by title substring",
    "app_integrations.focus_window": "name the foreground window",
    "app_integrations.list_open_apps": "enumerate open windows",
    "app_integrations.app_volume": "per-app volume read/set",
    "app_integrations.list_app_volumes": "list per-app volumes",
    "app_integrations.spotify_action": "Spotify media-key transport",
    "app_integrations.spotify_search_play": "desktop Spotify search and play",
    "spotify_api.queue": "real Spotify queue (Web API, Premium)",
    "spotify_api.playlists": "real Spotify playlists (Web API, Premium)",
    "spotify_api.play_playlist_by_name": "start a Spotify playlist (Web API, Premium)",
    "spotify_api.search_and_play": "Spotify search and play (Web API)",
    "hermes_bridge.skills": "list 72 installed Hermes skills",
    "hermes_bridge.memory_read": "read/append Hermes MEMORY.md and USER.md",
    "hermes_bridge.slack_manifest": "generate the Hermes Slack app manifest",
    "hermes_bridge.memory_provider_status": "memory provider status incl. Honcho",
    "email_integration": "Outlook/Mailbox mail read and send",
    "agency_client": "Agency OS mission state and outreach",
    "tunnel_remote": "Cloudflare quick tunnel for the phone link",
    "server._save_vault_entry": "local memory vault (remember X)",
    "server.api_system_status": "live battery/cpu/disk/net/ram metrics",
    "server.proactive": "proactive suggestion engine",
    "speech_stt": "speech-to-text and wake word",
    "datascience.load": "load CSV/TSV/JSON/Excel into a DataFrame",
    "datascience.describe": "column types, counts, sample values",
    "datascience.statistical_summary": "mean/median/stddev/skew/kurtosis/IQR/z-scores",
    "datascience.missing_values": "per-column null counts and percentages",
    "datascience.outliers": "IQR and z-score outlier detection",
    "datascience.correlations": "full correlation matrix with top pairs",
    "datascience.clean": "drop/dedupe/fill outliers and nulls (dry-run report)",
    "datascience.validate": "schema and range validation",
    "datascience.data_quality": "completeness/uniqueness/consistency score",
    "datascience.regression": "linear regression with R2 and coefficients",
    "datascience.classification": "logistic/tree classifier with accuracy report",
    "datascience.clustering": "k-means clustering with silhouette score",
    "datascience.forecast": "linear-trend and moving-average forecast",
    "datascience.trends": "direction and percent change over time",
    "datascience.pivot": "group-by aggregation table",
    "datascience.kpis": "numeric totals, averages, min/max, best row",
    "datascience.compare": "compare two datasets column by column",
    "datascience.anomaly_detection": "z-score and IQR anomaly detection",
    "datascience.chart": "render a PNG chart (line/bar/scatter/hist/pie/box/area)",
    "pdf_tools.info": "PDF page count, metadata, encryption",
    "pdf_tools.extract_text": "per-page PDF text extraction",
    "pdf_tools.search": "regex search across a PDF with page numbers",
    "pdf_tools.compare": "per-page text diff between two PDFs",
    "pdf_tools.merge": "concatenate PDFs",
    "pdf_tools.split": "split a PDF into single-page files",
    "pdf_tools.extract_pages": "write a page range to a new PDF",
    "pdf_tools.text_from_text": "build a text PDF (reportlab)",
    "file_intel.classify_file": "detect file type from content and extension",
    "file_intel.inventory": "folder inventory: counts, size, biggest type",
    "file_intel.find_duplicates": "SHA-256 duplicate groups across a tree",
    "file_intel.metadata": "filesystem size/dates and image/PDF/exif metadata",
    "file_intel.find_empty_files": "find 0-byte files",
    "file_intel.old_files": "find files untouched for N days",
    "file_intel.similar_names": "find near-duplicate filenames",
    "file_intel.rename_plan": "dry-run batch rename plan",
    "file_intel.rename_apply": "apply a rename plan (approval-gated)",
    "research_api.openalex_search": "OpenAlex paper search (no key)",
    "research_api.openalex_author": "author profile with h-index and citations",
    "research_api.openalex_citations": "works citing a given work",
    "research_api.openalex_related": "related works by topic",
    "research_api.open_access_pdf": "locate an open-access PDF",
    "research_api.crossref_lookup": "Crossref DOI metadata",
    "research_api.arxiv_by_id": "arXiv paper by arXiv ID",
    "research_api.paper_by_id": "resolve a paper by DOI/arXiv/OpenAlex ID",
    "research_api.search_papers": "multi-index paper search (OpenAlex+Crossref+arXiv)",
    "web_apis.weather": "current conditions and forecast (Open-Meteo, no key)",
    "web_apis.air_quality": "live air quality index (Open-Meteo, no key)",
    "web_apis.geocode": "place name to coordinates (Nominatim, no key)",
    "web_apis.reverse_geocode": "coordinates to place name (Nominatim)",
    "web_apis.nearby_places": "nearby POIs from OpenStreetMap Overpass",
    "web_apis.route": "route distance, duration and roads (OSRM, no key)",
    "web_apis.translate": "text translation (MyMemory, no key)",
    "web_apis.detect_language": "script and language detection",
    "knowledge_graph.build": "rebuild the local entity/link graph",
    "knowledge_graph.summarize": "top entities and links from local memory",
    "knowledge_graph.lookup": "recall everything recorded about an entity",
    "knowledge_graph.related": "closest co-mentioned neighbours of an entity",
    "ocr.ocr_image": "text recognition on images (Windows.Media.Ocr, no key)",
    "ocr.available": "report OCR engine status",
    "tasks.add_task": "add a task with natural-language due date and priority",
    "tasks.list_tasks": "list pending/completed tasks",
    "tasks.complete_task": "mark a task done",
    "tasks.uncomplete_task": "reopen a completed task",
    "tasks.update_task": "edit title, due date, priority, tags",
    "tasks.delete_task": "remove a task",
    "tasks.overdue": "tasks past their due date",
    "tasks.due_within": "tasks due inside N days",
    "tasks.reminder_digest": "upcoming task digest",
    "tasks.stats": "task counts by state and priority",
    "tasks.export_ics": "export tasks as an RFC 5545 calendar file",
    "safety.history": "list recorded actions",
    "safety.undo_last": "undo the most recent reversible action",
    "safety.request_approval": "hold a destructive action for user approval",
    "safety.resolve_approval": "approve or reject a held action",
    "safety.needs_approval": "check whether a kind requires approval",
    "workflows.create": "create a scheduled/file/idle automation",
    "workflows.run_now": "run an automation immediately",
    "workflows.tick": "evaluate due automations",
    "workflows.set_enabled": "enable or pause an automation",
    "tts_engine": "Edge TTS speech synthesis",
    "gesture_controller": " webcam gesture control",
    "chrome_bridge": "browser tab and page control",
}

_CATEGORIES = {
    "Advanced Intelligence & Reasoning": {
        "Deep reasoning": "M", "Multi-step planning": "M", "Goal decomposition": "M",
        "Decision-tree generation": "M", "Constraint solving": "M",
        "Pattern recognition": "M", "Anomaly detection": "M", "Deduction": "M",
        "Inductive reasoning": "M", "Hypothesis generation": "M",
        "Hypothesis testing": "M", "Scenario analysis": "M", "What-if analysis": "M",
        "Root-cause analysis": "M", "Tradeoff analysis": "M", "Risk analysis": "M",
        "Dependency analysis": "M", "Priority optimization": "M",
        "Resource allocation": "M", "Strategy generation": "M",
        "Counterargument generation": "M", "Assumption detection": "M",
        "Contradiction detection": "M", "Consistency checking": "M",
        "Confidence estimation": "M", "Uncertainty analysis": "M",
        "Decision support": "M", "Goal tracking": "S:no goal store wired",
        "Long-term planning": "S:no persistent planning store",
        "Autonomous task decomposition": "M",
    },
    "Personal Intelligence": {
        "User preference learning": "P:server.vault_save",
        "Habit recognition": "N", "Routine detection": "N", "Context awareness": "P:server.proactive",
        "Conversation continuity": "P:server.sessions", "Personal knowledge graph": "W:knowledge_graph (built from vault/tasks; local)",
        "Relationship graph": "W:knowledge_graph.related", "Project memory": "P:hermes_bridge.memory",
        "Preference memory": "P:server.vault_save", "Important-date memory": "N",
        "Contextual reminders": "P:server.proactive", "Proactive suggestions": "W:server.proactive",
        "Personalized recommendations": "M", "Personal dashboard": "W:public Agency OS",
        "Daily briefing": "S:no scheduled morning brief", "Weekly briefing": "N",
        "Monthly review": "N", "Goal monitoring": "N", "Habit tracking": "N",
        "Personal analytics": "N",
    },
    "Computer Control": {
        "Launch applications": "W:pc_actions.open_app", "Close applications": "W:pc_actions.close_window",
        "Switch windows": "W:app_integrations.focus_window",
        "Minimize/maximize windows": "P:pc_actions.show_desktop",
        "Window positioning": "N", "Multi-monitor control": "N",
        "Screenshot capture": "W:pc_actions.screenshot", "Screen analysis": "M",
        "OCR": "W:ocr.ocr_image (Windows.Media.Ocr, local, no key)",
        "Clipboard management": "W:pc_actions.clipboard_read+clipboard_write",
        "Keyboard automation": "P:pc_actions hotkeys only",
        "Mouse automation": "P:pyautogui in spotify fallback only",
        "File drag/drop automation": "N", "Desktop search": "P:pc_actions.browser_search",
        "Application search": "W:pc_actions.open_app", "Process monitoring": "W:pc_actions.list_processes",
        "CPU monitoring": "W:pc_actions.system_diagnostics",
        "RAM monitoring": "W:pc_actions.system_diagnostics",
        "GPU monitoring": "N", "Disk monitoring": "W:pc_actions.system_diagnostics",
        "Network monitoring": "W:pc_actions.system_diagnostics",
        "Battery monitoring": "W:pc_actions.system_diagnostics",
        "Device information": "W:pc_actions.system_diagnostics",
        "System diagnostics": "W:pc_actions.system_diagnostics",
        "Startup application management": "P:pc_actions.startup_apps (read-only)",
    },
    "File Intelligence": {
        "File search": "W:pc_actions.file_search", "Semantic file search": "N",
        "Duplicate detection": "W:file_intel.find_duplicates (SHA-256)",
        "File classification": "W:file_intel.classify_file",
        "Automatic folder organization": "P:file_intel.rename_plan (dry-run plan; apply is approval-gated)",
        "File renaming": "W:file_intel.rename_apply", "Batch renaming": "W:file_intel.rename_plan/rename_apply",
        "File tagging": "N", "File metadata extraction": "W:file_intel.metadata",
        "PDF extraction": "W:pdf_tools.extract_text", "PDF summarization": "P:pdf_tools.extract_text + LLM",
        "PDF comparison": "W:pdf_tools.compare", "PDF merging": "W:pdf_tools.merge",
        "PDF splitting": "W:pdf_tools.split", "PDF conversion": "N", "Document conversion": "N",
        "Image-to-text": "W:ocr.ocr_image", "Document-to-markdown": "P:pdf_tools.extract_text",
        "Archive management": "N", "Backup management": "N",
        "File cleanup suggestions": "W:file_intel.find_empty_files/old_files",
        "Large-file detection": "W:pc_actions.large_files",
        "Recent-file intelligence": "W:pc_actions.recent_files",
        "Project-folder analysis": "W:file_intel.inventory", "File version comparison": "N",
    },
    "Browser & Web Agent": {
        "Web search": "W:pc_actions.browser_search", "Deep research": "M",
        "Website summarization": "M", "Page extraction": "P:chrome_bridge",
        "Multi-page research": "M", "Source comparison": "M", "Fact verification": "M",
        "Citation collection": "N", "Website monitoring": "S:no scheduler for it",
        "Price monitoring": "S:no retailer accounts", "Product monitoring": "S:no retailer accounts",
        "News monitoring": "P:server /api/news (live RSS)",
        "Form filling": "P:chrome_bridge", "Website navigation": "W:pc_actions browser_*",
        "Web login assistance": "C:site credentials", "Table extraction": "N",
        "Data extraction": "P:chrome_bridge", "Article comparison": "M",
        "Search-result filtering": "M", "Research report generation": "M",
        "Website change detection": "N", "FAQ extraction": "M", "Documentation lookup": "M",
        "Web archive lookup": "S:no archive API key", "Research bookmarking": "N",
    },
    "Research Lab": {
        "Literature search": "W:research_api.search_papers (OpenAlex + Crossref + arXiv)",
        "Paper discovery": "W:research_api.openalex_search",
        "Paper summarization": "P:research_api.paper_by_id (abstract) + LLM",
        "Paper comparison": "P:research_api (multi-search) + LLM", "Citation extraction": "W:research_api.crossref_lookup",
        "Research timeline": "P:research_api (date fields) + LLM", "Research question generation": "M",
        "Literature-gap detection": "M", "Source credibility analysis": "M",
        "Evidence extraction": "M", "Claim verification": "M",
        "Dataset discovery": "N:no dataset registry wired", "Research note organization": "P:server.vault_save",
        "Bibliography generation": "W:research_api (citation fields)", "Citation formatting": "M",
        "Experimental planning": "M", "Hypothesis management": "M",
        "Research project tracking": "N", "Research presentation creation": "N",
        "Automated research briefs": "P:research_api + LLM",
    },
    "Programming": {
        "Code generation": "M", "Code explanation": "M", "Code debugging": "M",
        "Code refactoring": "M", "Code optimization": "M", "Code review": "M",
        "Unit-test generation": "M", "Integration-test generation": "M",
        "Test execution": "P:terminal action runs the command",
        "Bug reproduction": "M", "Error-log analysis": "M", "Stack-trace analysis": "M",
        "Dependency analysis": "M", "Package discovery": "M", "Documentation generation": "M",
        "API generation": "M", "API testing": "M", "Database querying": "C:DB credentials",
        "SQL generation": "M", "Regex generation": "M", "Shell scripting": "M",
        "Git assistance": "P:terminal action runs git", "Commit generation": "M",
        "PR description generation": "M", "Repository analysis": "M",
        "Architecture analysis": "M", "Dependency updates": "M", "Migration assistance": "M",
        "Security scanning": "M", "Performance profiling": "M",
    },
    "Software Engineering Agent": {
        "Project scaffolding": "M", "Feature implementation": "M", "Issue analysis": "M",
        "Issue fixing": "M", "Codebase mapping": "M", "Architecture planning": "M",
        "Refactoring plans": "M", "Technical-debt detection": "M",
        "Documentation auditing": "M", "API compatibility checking": "M",
        "Build troubleshooting": "P:terminal action", "CI troubleshooting": "P:terminal action",
        "Deployment troubleshooting": "P:terminal action", "Log monitoring": "P:terminal action",
        "Release-note generation": "M", "Changelog generation": "M", "Semantic versioning": "M",
        "Environment configuration": "M", "Docker assistance": "S:Docker not installed",
        "Cloud deployment assistance": "C:cloud account", "Database migration planning": "M",
        "Performance optimization": "M", "Test coverage analysis": "M",
        "Code-quality analysis": "M", "Developer onboarding": "M",
    },
    "Data Science": {
        "CSV analysis": "W:datascience.load/describe", "Excel analysis": "W:datascience.load (openpyxl)",
        "Data cleaning": "W:datascience.clean", "Missing-value detection": "W:datascience.missing_values",
        "Outlier detection": "W:datascience.outliers", "Data transformation": "P:datascience.clean/kpis",
        "Statistical analysis": "W:datascience.statistical_summary", "Correlation analysis": "W:datascience.correlations",
        "Regression": "W:datascience.regression", "Forecasting": "W:datascience.forecast",
        "Clustering": "W:datascience.clustering", "Classification": "W:datascience.classification",
        "Dataset visualization": "W:datascience.chart", "Chart generation": "W:datascience.chart (7 kinds, PNG)",
        "Dashboard generation": "N",
        "Data summarization": "W:datascience.describe", "Pivot analysis": "W:datascience.pivot",
        "KPI calculation": "W:datascience.kpis", "Trend detection": "W:datascience.trends",
        "Anomaly detection": "W:datascience.anomaly_detection", "Data pipeline design": "M",
        "Dataset comparison": "W:datascience.compare", "Automated reports": "M",
        "Data validation": "W:datascience.validate", "Data quality scoring": "W:datascience.data_quality",
    },
    "Business Intelligence": {
        "KPI tracking": "N", "Sales analysis": "S:no sales data source",
        "Revenue analysis": "S:no revenue data source", "Customer analysis": "S:no CRM",
        "Market research": "M", "Competitor research": "M", "SWOT analysis": "M",
        "Business-plan generation": "M", "Strategy analysis": "M", "Process optimization": "M",
        "Operations analysis": "M", "Product analysis": "M", "Customer segmentation": "M",
        "Churn analysis": "S:no customer data", "Pricing analysis": "M",
        "Forecasting": "M", "Scenario modeling": "M", "Executive briefing": "M",
        "Meeting intelligence": "S:no calendar or meeting audio", "Business report generation": "M",
    },
    "Writing": {
        "Blog writing": "M", "Article writing": "M", "Technical writing": "M",
        "Documentation": "M", "Email drafting": "P:email_integration",
        "Proposal writing": "M", "Report writing": "M", "Essay assistance": "M",
        "Script writing": "M", "Story writing": "M", "Copywriting": "M", "Editing": "M",
        "Proofreading": "M", "Tone transformation": "M", "Simplification": "M",
        "Expansion": "M", "Summarization": "M", "Paraphrasing": "M",
        "Headline generation": "M", "Outline generation": "M", "Brainstorming": "M",
        "Grammar correction": "M", "Style analysis": "M", "Readability analysis": "M",
        "Translation": "W:web_apis.translate (MyMemory, no key)",
    },
    "Creative Studio": {
        "Idea generation": "M", "Character creation": "M", "Worldbuilding": "M",
        "Story planning": "M", "Plot analysis": "M", "Dialogue writing": "M",
        "Creative prompts": "M", "Brand-name generation": "M", "Logo concept generation": "M",
        "Design briefs": "M", "Moodboard concepts": "M", "Presentation concepts": "M",
        "Poster concepts": "M", "Thumbnail concepts": "M", "Social-media concepts": "M",
        "Video concepts": "M", "Advertisement concepts": "M", "Product concepts": "M",
        "UI concepts": "M", "Creative critique": "M",
    },
    "Video Production": {
        "Video idea generation": "M", "Script generation": "M", "Storyboard generation": "M",
        "Shot-list generation": "M", "Scene planning": "M", "Voiceover scripts": "M",
        "Subtitle generation": "M", "Caption generation": "M", "Video summarization": "S:no video decoding",
        "Video transcription": "S:no video decoding (audio STT only)", "Chapter generation": "M",
        "Highlight detection": "N", "Clip identification": "N", "Title generation": "M",
        "Thumbnail concepts": "M", "Metadata generation": "M", "Content repurposing": "M",
        "Long-video to short-video planning": "M", "Podcast to video conversion": "M",
        "Video quality analysis": "N",
    },
    "Music": {
        "Music discovery": "S:Spotify account not connected",
        "Playlist generation": "S:Spotify Premium not connected",
        "Mood-based playlists": "S:Spotify Premium not connected",
        "Genre discovery": "S:Spotify account not connected",
        "Artist discovery": "S:Spotify account not connected",
        "Music history": "N", "Song analysis": "S:needs audio analysis",
        "Album analysis": "P:spotify_api metadata when connected",
        "Music recommendations": "S:Spotify account not connected",
        "Listening statistics": "N", "Playlist organization": "S:needs connected account",
        "Music-library cleanup": "N", "Genre classification": "N",
        "Artist similarity": "N", "Music discovery radar": "N",
    },
    "Gaming": {
        "Game recommendations": "M", "Game discovery": "M", "Game-library organization": "N",
        "Game information lookup": "M", "Build planning": "M", "Strategy explanations": "M",
        "Quest tracking": "N", "Achievement tracking": "N", "Game-stat analysis": "S:no game telemetry",
        "Patch-note summaries": "M", "Game-update monitoring": "S:no scheduler for it",
        "Esports information": "M", "Tournament tracking": "N",
        "Game-server monitoring": "N", "Gaming-news briefing": "M",
    },
    "Education": {
        "Tutor mode": "M", "Concept explanation": "M", "Socratic questioning": "M",
        "Homework assistance": "M", "Practice-question generation": "M",
        "Quiz generation": "M", "Flashcard generation": "M",
        "Spaced-repetition planning": "M", "Study-plan generation": "M",
        "Exam revision": "M", "Mistake analysis": "N",
        "Learning-progress tracking": "N", "Vocabulary training": "M",
        "Language practice": "M", "Pronunciation practice": "S:no pronunciation scoring",
        "Math solving": "M", "Physics problem solving": "M", "Chemistry assistance": "M",
        "Biology assistance": "M", "History assistance": "M", "Geography assistance": "M",
        "Computer-science tutoring": "M",
    },
    "Languages": {
        "Translation": "W:web_apis.translate (MyMemory, no key)", "Transcription": "W:speech_stt",
        "Language detection": "W:web_apis.detect_language", "Grammar correction": "M", "Vocabulary building": "M",
        "Pronunciation coaching": "S:no pronunciation scoring", "Conversation practice": "M",
        "Accent explanation": "M", "Idiom explanation": "M", "Slang explanation": "M",
        "Dictionary lookup": "M", "Etymology lookup": "M", "Multilingual search": "M",
        "Bilingual document conversion": "N", "Language-learning plans": "M",
        "Reading practice": "M", "Writing practice": "M", "Speaking practice": "P:tts_engine speaks back",
    },
    "Productivity": {
        "Task management": "W:tasks.add_task/list_tasks/complete_task", "Task prioritization": "W:tasks (low/medium/high/urgent)",
        "Calendar management": "P:tasks.export_ics (ICS; no Outlook/Google OAuth)",
        "Meeting preparation": "M", "Meeting summaries": "S:no meeting audio source",
        "Action-item extraction": "M", "Deadline tracking": "W:tasks.overdue/due_within",
        "Reminder management": "W:tasks.reminder_digest",
        "Daily planning": "M", "Weekly planning": "M", "Focus sessions": "P:pc_actions.lock_screen_timer",
        "Project planning": "M", "Kanban management": "N", "Routine automation": "W:workflows (28-action whitelist)",
        "Time blocking": "N", "Productivity analytics": "N", "Inbox organization": "P:email_integration",
        "Notification summaries": "N", "End-of-day review": "N", "Morning briefing": "S:no scheduler for it",
    },
    "Smart Home": {
        "Lights": "S:no smart-home devices", "Fans": "S:no smart-home devices",
        "AC": "S:no smart-home devices", "Thermostats": "S:no smart-home devices",
        "TVs": "S:no smart-home devices", "Speakers": "P:app_volume (PC audio only)",
        "Cameras": "S:no smart-home devices", "Doorbells": "S:no smart-home devices",
        "Smart plugs": "S:no smart-home devices", "Sensors": "S:no smart-home devices",
        "Curtains": "S:no smart-home devices", "Scenes": "S:no smart-home devices",
        "Home modes": "S:no smart-home devices", "Energy monitoring": "S:no smart meter",
        "Device health": "P:pc_actions.system_diagnostics (PC only)", "Automation rules": "N",
        "Presence detection": "N", "Room control": "S:no smart-home devices",
        "Home dashboard": "N", "Emergency alerts": "N",
    },
    "Communication": {
        "Email organization": "P:email_integration", "Email summarization": "P:email_integration",
        "Email search": "P:email_integration", "Draft replies": "M",
        "Inbox prioritization": "M", "Meeting invitations": "N", "Contact search": "N",
        "Notification summarization": "N", "Message drafting": "M",
        "Message categorization": "M", "Communication reminders": "N",
        "Follow-up tracking": "N", "Conversation summaries": "N", "Contact notes": "N",
        "Communication history": "N",
    },
    "Shopping & Products": {
        "Product discovery": "M", "Product comparison": "M",
        "Specification comparison": "M", "Price comparison": "M", "Price tracking": "S:no retailer accounts",
        "Review summarization": "S:no retailer access", "Review sentiment analysis": "S:no review source",
        "Product research": "M", "Alternative discovery": "M", "Compatibility checking": "M",
        "Shopping-list management": "N", "Deal monitoring": "S:no retailer accounts",
        "Wishlist management": "N", "Product availability monitoring": "S:no retailer accounts",
        "Purchase research": "M",
    },
    "Travel": {
        "Destination research": "M", "Trip planning": "M", "Itinerary generation": "M",
        "Hotel research": "M", "Transportation research": "M", "Route planning": "W:web_apis.route",
        "Attraction discovery": "M", "Restaurant discovery": "M", "Packing lists": "M",
        "Travel checklists": "M", "Local-language assistance": "M",
        "Travel-budget planning": "M", "Weather-aware planning": "W:web_apis.weather (Open-Meteo, no key)",
        "Trip document organization": "P:file_intel.inventory", "Travel reminders": "W:tasks.reminder_digest",
    },
    "Maps & Location": {
        "Place search": "W:web_apis.geocode (Nominatim, no key)",
        "Nearby-place discovery": "P:web_apis.nearby_places (Overpass; free servers rate-limit under load)",
        "Route planning": "W:web_apis.route (OSRM, no key; driving/walking/cycling)",
        "Distance calculation": "W:web_apis.route",
        "Travel-time estimation": "W:web_apis.route (OSRM duration)",
        "Area exploration": "P:web_apis.nearby_places",
        "Place comparison": "M", "Location-based reminders": "P:workflows (new-file/daily triggers)",
        "Geofencing workflows": "N:no continuous location daemon",
        "Local event discovery": "S:no events API",
    },
    "Personal Finance": {
        "Expense tracking": "N", "Budget planning": "M", "Spending categorization": "N",
        "Subscription tracking": "N", "Bill reminders": "N", "Financial summaries": "N",
        "Cash-flow analysis": "S:no account data", "Savings-goal tracking": "N",
        "Expense anomaly detection": "N", "Receipt organization": "N",
        "Invoice extraction": "N", "Tax-document organization": "N",
        "Financial-document summarization": "M",
    },
    "Knowledge Graph": {
        "Entity extraction": "W:knowledge_graph (regex NER, local)",
        "Relationship extraction": "W:knowledge_graph (co-occurrence links)",
        "Knowledge graph construction": "W:knowledge_graph.build",
        "Personal knowledge graph": "W:knowledge_graph.summarize",
        "Topic graph generation": "W:knowledge_graph.related", "Concept linking": "P:knowledge_graph",
        "Knowledge-gap detection": "M",
        "Fact linking": "W:knowledge_graph.lookup", "Timeline construction": "M",
        "Entity disambiguation": "P:knowledge_graph (best-casing merge)", "Knowledge-base search": "P:pc_actions.file_search",
        "Automatic knowledge updates": "W:knowledge_graph (rebuilt on vault/task change)",
    },
    "Security & Privacy": {
        "Permission management": "N", "Secret detection": "W:repo secret scan (dev-time)",
        "Credential protection": "P:data/keys.json is git-ignored",
        "Sensitive-data detection": "M", "Privacy checks": "M",
        "Suspicious-link detection": "M", "Phishing detection": "M",
        "File-permission auditing": "N", "Application-permission auditing": "N",
        "Security-event monitoring": "N", "Login monitoring": "N",
        "Device-security status": "P:pc_actions.system_diagnostics", "Privacy-report generation": "M",
        "Data-access logging": "P:server request log", "Action confirmation system": "N",
    },
    "Automation": {
        "Scheduled workflows": "S:Hermes cron exists but its agent loop cannot run on this key",
        "Event-triggered workflows": "N", "File-triggered workflows": "N",
        "Time-triggered workflows": "N", "Email-triggered workflows": "N",
        "Web-triggered workflows": "N", "Multi-step automation": "P:server chained actions",
        "Conditional workflows": "N", "Retry handling": "N", "Failure recovery": "N",
        "Workflow templates": "N", "Workflow generation": "M", "Workflow debugging": "M",
        "Workflow monitoring": "N", "Automation history": "P:server action history",
    },
    "Autonomous Agent Skills": {
        "Goal execution": "M", "Autonomous research": "M", "Autonomous browsing": "P:chrome_bridge",
        "Autonomous coding": "M", "Autonomous testing": "P:terminal action",
        "Autonomous debugging": "M", "Autonomous file organization": "N",
        "Autonomous project setup": "M", "Autonomous monitoring": "P:server.proactive",
        "Autonomous reporting": "M", "Multi-agent delegation": "S:Hermes delegation needs the agent loop",
        "Agent collaboration": "S:Hermes delegation needs the agent loop",
        "Agent verification": "N", "Task recovery": "N", "Long-running tasks": "P:background threads",
        "Background jobs": "P:server background threads", "Progress reporting": "P:server.progress",
        "Human approval checkpoints": "N", "Failure diagnosis": "M", "Self-evaluation": "N",
    },
    "Futuristic JARVIS Skills": {
        "Predictive task suggestions": "P:server.proactive", "Proactive information retrieval": "P:server.proactive",
        "Context-aware recommendations": "M", "Situation awareness": "P:server.system_status",
        "Ambient assistant mode": "P:speech_stt wake word", "Voice activation": "W:speech_stt wake word",
        "Multi-device synchronization": "P:tunnel_remote phone link",
        "Cross-device continuity": "P:tunnel_remote", "Personal AI operating system": "P:Agency OS UI",
        "AI-generated workflows": "M", "Automatic skill discovery": "W:hermes_bridge.skills",
        "Automatic skill installation": "N", "Skill dependency resolution": "N",
        "Skill health monitoring": "P:hermes_bridge.status", "Skill performance analytics": "N",
        "Self-improving workflows": "N", "Personal command language": "W:server synonym catalog",
        "Natural-language macros": "P:server chained actions", "Persistent projects": "P:open_project",
        "Mission-control dashboard": "W:Agency OS UI",
    },
    "Multimodal Vision": {
        "Object recognition": "M", "Image understanding": "S:no vision model wired",
        "Screenshot understanding": "W:pc_actions.screenshot then read the file",
        "UI understanding": "S:no vision model wired", "Chart understanding": "S:no vision model wired",
        "Diagram understanding": "S:no vision model wired", "Document vision": "W:ocr.ocr_image on page/image (no vision LLM)",
        "Handwriting recognition": "S:Windows OCR does handwriting only on device-specific packs", "OCR": "W:ocr.ocr_image (Windows.Media.Ocr, local, no key)",
        "Visual comparison": "N", "Image search": "M", "Scene analysis": "S:no vision model",
        "Visual question answering": "S:no vision model", "Image classification": "S:no vision model",
        "Visual anomaly detection": "N",
    },
    "Voice JARVIS": {
        "Wake-word detection": "W:speech_stt", "Voice commands": "W:speech_stt",
        "Continuous conversation": "P:speech_stt session mode", "Speaker identification": "N",
        "Voice activity detection": "P:speech_stt VAD", "Speech transcription": "W:speech_stt",
        "Speech synthesis": "W:tts_engine", "Voice selection": "P:app.js voice picker",
        "Speaking-speed control": "P:tts_engine rate", "Interruption handling": "P:speech_stt barge-in",
        "Voice confirmation": "N", "Voice shortcuts": "N", "Voice macros": "P:server chained actions",
        "Background listening modes": "P:speech_stt", "Context-aware responses": "M",
    },
    "JARVIS magic layer": {
        "Morning intelligence briefing": "S:no scheduler for it",
        "Automatic daily agenda": "S:no calendar connected",
        "What should I know briefing": "M", "What did I miss briefing": "S:no activity log source",
        "Personal command macros": "P:server chained actions",
        "Natural-language computer control": "W:pc_actions + server router",
        "One-command multi-action execution": "P:server chained actions",
        "Proactive reminders based on context": "P:server.proactive",
        "Automatic project monitoring": "P:pc_actions.system_diagnostics",
        "Automatic website monitoring": "S:no scheduler for it",
        "Automatic news monitoring": "P:server /api/news",
        "Automatic research agents": "M",
        "Background task agents": "P:server background threads",
        "Personal knowledge graph": "W:knowledge_graph", "Long-term project memory": "P:server.vault_save",
        "Cross-device memory": "P:tunnel_remote", "Context-aware skill selection": "P:server router",
        "Automatic workflow creation": "M", "Skill chaining": "P:server chained actions",
        "Skill marketplace/plugin system": "P:hermes_bridge.skills (read-only)",
        "Agent-to-agent delegation": "S:Hermes delegation needs the agent loop",
        "Human approval checkpoints": "N", "Undo/recovery system": "N",
        "Action history": "W:server action history", "Explain-what-I-did mode": "P:server action history",
        "Watch this for me mode": "S:no scheduler for it",
        "Handle this until it's done mode": "M",
        "Keep me updated mode": "P:server background threads",
        "Prepare everything mode": "M", "Find and fix it mode": "M",
    },
}

_STATUS_LEGEND = {
    "W": "working - real deterministic executor",
    "P": "partial - real executor, narrower than requested",
    "M": "model - genuinely handled by Groq in conversation",
    "C": "needs credential",
    "S": "needs service, hardware, or an integration that does not exist here",
    "N": "not implemented",
}


def _classify(code: str) -> tuple[str, str]:
    kind, _, detail = code.partition(":")
    return kind, detail


def all_capabilities() -> list:
    out = []
    for category, caps in _CATEGORIES.items():
        for name, code in caps.items():
            kind, detail = _classify(code)
            out.append({
                "category": category, "capability": name, "status": kind,
                "backing": detail,
                "description": EXECUTORS.get(detail, ""),
            })
    return out


def summary() -> dict:
    caps = all_capabilities()
    counts = {}
    for c in caps:
        counts[c["status"]] = counts.get(c["status"], 0) + 1
    return {
        "total": len(caps),
        "categories": len(_CATEGORIES),
        "by_status": {k: counts.get(k, 0) for k in ("W", "P", "M", "C", "S", "N")},
        "legend": _STATUS_LEGEND,
        "real_executors": len(EXECUTORS),
        "note": (
            "Capabilities marked M are real but generative: the Groq model handles "
            "them in conversation. W and P have deterministic executors. C, S and N "
            "are honest gaps -- JENNY reports them instead of pretending."
        ),
    }


def lookup(name: str) -> dict | None:
    target = (name or "").strip().lower()
    for c in all_capabilities():
        if c["capability"].lower() == target:
            return c
    return None
